name: Test Backend

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - client/** # Should only run on backend changes
      - .gitignore
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r "./server/requirements.txt"
      - name: Test with pytest
        run: |
          pytest
