name: Test Client

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - backend/** # Should only run on client changes
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLIENT_ID: "test"
      NEXT_PUBLIC_REDIRECT_URI: "http://localhost:3000/auth/login"
      NEXT_PUBLIC_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize?client_id=test&redirect_uri=http://localhost:3000/auth/login"
      NEXT_PUBLIC_DOMAIN: "https://gitinspire.vercel.app"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000"
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [16, 18, 19]
    name: Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          npm ci
          npm test
